version: '3.3'

services:
  db:
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=fcode
      - TZ=Etc/GMT
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    restart: always
    volumes:
      - banco:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080

volumes:
  banco:
